- name: Run Alert Morning (08:00 EAT)
        if: github.event.schedule == '0 5 * * 1-5' || github.event_name == 'workflow_dispatch'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py morning

      - name: Run Alert London Open (11:00 EAT)
        if: github.event.schedule == '0 8 * * 1-5'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py london_open

      - name: Run Alert NY Open (16:30 EAT)
        if: github.event.schedule == '30 13 * * 1-5'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py ny_open

      - name: Run Alert London Close (19:00 EAT)
        if: github.event.schedule == '0 16 * * 1-5'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py london_close
